### ISSUE TITLE
SolrCoreService::updateItems() fails when $items is null

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#180] opened 2019-12-20 00:40 UTC
**Describe the bug**

For some reason `SolrCoreService::updateItems() ` is being passed `null` as the `$items` param, when running the `dev/tasks/SolrClearDirtyClasses` from the CLI and browser. When this happens I see the following error:

> ERROR [Notice]: Trying to get property 'ClassName' of non-object
IN GET dev/tasks/SolrClearDirtyClasses
Line 150 in /vagrant/vendor/firesphere/solr-search/src/Services/SolrCoreService.php

**To Reproduce**

* [OK] Configure
* [OK] Index
* [OK] Search
* [OK] dev/tasks/SolrClearDirtyClasses

**Expected behavior**

No errors are observed and I can run the dev/tasks/SolrClearDirtyClasses task without issue.

**Additional context**

Interestingly, running the task still seemed to clear out records with dirty IDs, with ref to the CMS UI.

**Comment by Firesphere** [comment] 2019-12-20 03:34
Interesting, did you happen to have deleted some pages that were marked as Dirty?

**Comment by phptek** [comment] 2019-12-20 03:46
Possibly. I can't rule it out. How often is that task supposed to be run?

**Comment by Firesphere** [comment] 2019-12-20 03:52
SolrIndexTask/Job should only be run when you want to reindex everything. Or, if you want to reindex a specific group again.

The Dirty task should probably be run more often, but it depends on how often the content is changed. It's up to the team to decide that. Depending on the volatility of the content. I don't have any specific recommendations for that.

**Comment by Firesphere** [comment] 2019-12-20 05:41
Could you get the full stacktrace of that error you are getting @phptek ?

I somehow can't reproduce it, because I seem to be unable to get Dirty Classes...

**Comment by Firesphere** [comment] 2019-12-20 06:48
Yep, confirmed "bug?", it is not actually a problem, the indexing runs out of bounds for some reason. Fixing that asap in #181

**Comment by Firesphere** [comment] 2019-12-20 20:53
Sorry, #182

**Closed** 2019-12-20 20:52 UTC
Labels: Bug?
